name: Create a (Pre)release on NuGet

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

jobs:
  release-nuget:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify commit exists in origin/main (optional)
        continue-on-error: true
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Get version information from tag
        id: get_version
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}".TrimStart("v")
          Write-Output "version-without-v=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Pack NuGet package
        run: dotnet pack Plugin.Maui.LatestVersion/Plugin.Maui.LatestVersion/Plugin.Maui.LatestVersion.csproj -c Release -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}

      - name: Push to NuGet.org
        run: dotnet nuget push Plugin.Maui.LatestVersion/Plugin.Maui.LatestVersion/bin/Release/Plugin.Maui.LatestVersion.${{ steps.get_version.outputs.version-without-v }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
